baseurl: "http://nickvorobiov.com/"
url: "http://nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - '*.scss'
yandex_metrika: 36255245
google_analytics: UA-46456269-10
permalink: /:title/
export_logo: /images/icon/social_photo.jpg

title: "Блог Николая Воробьёва"
description: "Сделаю из тебя победителя"
keywords: "#ШоуВоробьёва"
author: "Николай Воробьёв"

gems: [jekyll-paginate]
paginate: 20

fb_app_id: 255302648202942
vk_app_id: 5628006
#vk_app_id: 4569992 # 127.0.0.1

post_pictures: /images/post/
array: []

collections:
  books:
    output: true
    permalink: /book/:path/

defaults:
  - scope:
      path: ""
      type: books
    values:
      layout: book
      subtitle: Книга Николая Воробьёва
