baseurl: ""
url: "http://nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - '*.scss'
yandex_metrika: 36255245
google_analytics: UA-46456269-10
permalink: /:title/

title: "Блог Николая Воробьёва"
description: "Сделаю из тебя победителя"
keywords: "#ШоуВоробьёва"
author: "Николай Воробьёв"

gems: [jekyll-paginate]
paginate: 20
